accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.login, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),

    path('', views.home, name = "home"),
    path('user/', views.userPage, name = "user_page"),
    path('account/', views.accountSettings, name = "account"),
    path('products/', views.products, name = "products"),
    path('customer/<int:pk>', views.customer, name = "customer"),

    path('create_product/', views.createProducts, name = "create_product"),
    path('create_order/<int:pk>', views.createOrder, name = "create_order"),
    path('update_order/<int:pk>', views.updateOrder, name = "update_order"),
    path('delete_order/<int:pk>', views.deleteOrder, name = "delete_order"),

    path('upload_pdf', views.uploadPdf, name="upload"),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router
from rest_framework.authtoken import views
from django.conf.urls.static import static
from django.conf import settings
from accounts.api import api_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('api/', include(router.urls)),
    # path('api/', api_views.apiProductsView),
    path('api-token-auth/', views.obtain_auth_token, name = 'api-token-auth'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    name = models.CharField(max_length = 200, null = True)
    phone = models.CharField(max_length = 200, null = True)
    email = models.CharField(max_length = 200, null = True)
    profile_pic = models.ImageField(default = "user.svg", null = True, blank = True)
    date_created = models.DateTimeField(auto_now_add = True, null = True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length = 200, null = True)

    def __str__(self):
        return self.name

class Product(models.Model):
    CATEGORY = [
		('Indoor', 'Indoor'),
		('Out Door', 'Out Door'),
	]
    name = models.CharField(max_length = 200, null = True)
    price = models.FloatField(null = True)
    category = models.CharField(max_length = 200, null = True, choices = CATEGORY)
    description = models.CharField(max_length = 200, null = True, blank = True)
    date_created = models.DateTimeField(auto_now_add = True, null = True)
    tag = models.ManyToManyField(Tag)
    class Meta:
        permissions = [
            ("change_product_price", "can change product price only")
        ]
    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS = [
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    ]
    customer = models.ForeignKey(Customer, null = True, on_delete = models.SET_NULL)
    product = models.ForeignKey(Product, null = True, on_delete = models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add = True, null = True)
    status = models.CharField(max_length = 200, null = True, choices = STATUS)

    def __str__(self):
        return self.product.name

    def getProductName(self):
        return self.product.name

    def getDateTime(self):
        return self.date_created.strftime("@ %H:%M:%S on %m/%d/%Y")

class FileUpload(models.Model):
    title = models.CharField(max_length = 80, null = True)
    file = models.FileField(null = True, upload_to='documents/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    date_created = models.DateTimeField(auto_now_add = True, null = True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Customer, Order, Product, FileUpload

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fileds = '__all__'
        exclude = ['user']

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UploadPdfForm(ModelForm):
    class Meta:
        model = FileUpload
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory, modelformset_factory

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import login as user_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from django.contrib import messages

from .models import *
from .forms import OrderForm, CreateUserForm, CustomerForm, ProductForm, UploadPdfForm
from .filters import OrderFilter
from .decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.
@unauthenticated_user
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(user.email)
            userName = form.cleaned_data.get('username')

            group = Group.objects.get(name='customer')
            user.groups.add(group)
			#Added username after video because of error returning customer name if not added
            Customer.objects.create(
            	user=user,
            	name=user.username,
                email=user.email,
            )

            messages.success(request, 'User created for ' + userName)

            return redirect('accounts:login')

    context = {'form': form}
    return render(request, 'accounts/register.html', context)

@unauthenticated_user
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username = username.strip(), password = password)

        if user is not None:
            user_login(request, user)
            return redirect('accounts:home')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'accounts/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

@login_required(login_url = 'accounts:login')
@admin_only
def home(request):
    customers = Customer.objects.all()
    orders = Order.objects.all()

    total_customers = customers.count()

    total_orders = orders.count()
    pending = orders.filter(status='Pending').count()
    delivered = orders.filter(status='Delivered').count()

    context = {
        'customers': customers,
        'orders': orders,
        'total_orders': total_orders,
        'pending': pending,
        'delivered': delivered,
    }

    return render(request, 'accounts/dashboard.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['customer'])
def userPage(request):
    orders = request.user.customer.order_set.all()
    total_orders = orders.count()
    pending = orders.filter(status='Pending').count()
    delivered = orders.filter(status='Delivered').count()

    context = {
        'orders': orders,
        'total_orders': total_orders,
        'pending': pending,
        'delivered': delivered,
    }
    return render(request, 'accounts/user.html', context)

# @login_required(login_url='login')
# @allowed_users(allowed_roles=['customer'])
def accountSettings(request):
    customer = request.user.customer
    form = CustomerForm(instance = customer)

    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance = customer)
        if form.is_valid:
            form.save()

    context = {'form': form}
    return render(request, 'accounts/account_settings.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def products(request):
    products = Product.objects.all()
    return render(request, 'accounts/products.html', {'products': products})

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def createProducts(request):
    ProductFormSet = modelformset_factory(Product, fields = ('name', 'price', 'category', 'tag'), extra = 5)
    formset = ProductFormSet(queryset = Product.objects.none())

    if request.method == 'POST':
        formset = ProductFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('accounts:products')

    context = {'form': formset}
    return render(request, 'accounts/product_form.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def customer(request, pk):
    customer = Customer.objects.get(id=pk)

    orders = customer.order_set.all()
    orders_count = orders.count()

    myFilter = OrderFilter(request.GET, queryset = orders)
    orders = myFilter.qs

    context = {'customer': customer, 'orders': orders, 'orders_count': orders_count, 'myFilter': myFilter}

    return render(request, 'accounts/customer.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def createOrder(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields = ('product', 'status'), extra = 10)
    customer = Customer.objects.get(id = pk)
    formset = OrderFormSet(queryset = Order.objects.none(), instance = customer)

    if request.method == 'POST':
        formset = OrderFormSet(request.POST, instance = customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')

    context = {'form': formset}
    return render(request, 'accounts/order_form.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def updateOrder(request, pk):
    order = Order.objects.get(id = pk)
    form = OrderForm(instance = order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance = order)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form': form}
    return render(request, 'accounts/order_form.html', context)

@login_required(login_url = 'accounts:login')
@allowed_users(allowed_roles = ['admin'])
def deleteOrder(request, pk):
    order = Order.objects.get(id = pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/')
    context = {'order': order}
    return render(request, 'accounts/delete.html', context)

def uploadPdf(request):
    UploadFormSet = modelformset_factory(FileUpload, fields = ('title', 'file',))
    formset = UploadFormSet(queryset = FileUpload.objects.none())

    if request.method == 'POST':
        formset = UploadFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'File uploaded successfully')
            return redirect('accounts:upload')
        else:
            formset = UploadPdfForm()

    context = {'form': formset}
    return render(request, 'accounts/upload_form.html', context)

accounts/templates/accounts/account_settings.html
{%  extends 'accounts/base_accounts.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'accounts:home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >

		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">

			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}

			  <input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/base_accounts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

</head>
<body>
    {% include 'accounts/navbar.html' %}

    <div class="container-fluid">

        {% block content %}{% endblock %}

      <hr>

      <h5>Little Footer</h5>
      <a class="btn btn-sm btn-primary"href="{% url 'accounts:upload' %}">Upload page</a>
      <hr>
      <embed src="images/documents/W8BENE_TIPS_PAIDAPP.pdf" width="800px" height="2100px" />
    </div>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/customer.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}

	<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info btn-sm btn-block" href="">Update Customer</a>
			<a class="btn btn-outline-primary btn-sm btn-block" href="{% url 'accounts:create_order' pk=customer.id %}">Place Order</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email: {{customer.email}}</p>
			<p>Phone: {{customer.phone}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{orders_count}}</h1>
		</div>
	</div>
</div>

<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
					{{myFilter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>

</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>

				{% for order in orders %}
					<tr>
						<td>{{order.product}}</td>
						<td>{{order.product.category}}</td>
						<td>{{order.date_created}}</td>
						<td>{{order.status}}</td>
						<td><a class="btn btn-info btn-sm" href="{% url 'accounts:update_order' pk=order.id %}">Update</a></td>
						<td><a class="btn btn-danger btn-sm" href="{% url 'accounts:delete_order' pk=order.id %}">Delete</a></td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}

{%  include 'accounts/status.html' %}

<br>
<div class="row">
    <div class="col-5">
        <h5>CUSTOMERS</h5>
        <hr>
        <div class="card card-body">
            <!-- <a class="btn btn-primary btn-sm btn-block" href="">Create Customer</a> -->
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Customer</th>
                    <th>Phone</th>
                </tr>

                {% for c in customers %}
                  <tr>
                    <td><a class="btn btn-info btn-sm" href="{% url 'accounts:customer' c.id %}">View</a></td>
                    <td>{{c.name}}</td>
                    <td>{{c.phone}}</td>
                  </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5>LAST ORDERS</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>

                {% for o in orders %}
                  <tr>
                    <td>{{o.product}}</td>
                    <td>{{o.date_created}}</td>
                    <td>{{o.status}}</td>
                    <td><a class="btn btn-info btn-sm" href="{% url 'accounts:update_order' pk=o.id %}">Update</a></td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'accounts:delete_order' pk=o.id %}">Delete</a></td>
                  </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/base_accounts.html' %}
{% load static %}

{% block content %}

<br>
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <p>Are you sure you want to delete "{{order}}"</p>

      <form action="{% url 'accounts:delete_order' pk=order.id %}" method="POST">
        {% csrf_token %}

        <a class="btn btn-warning" href="{% url 'accounts:home' %}">Cancel</a>

        <input class="btn btn-danger" type="submit" name="Confirm">
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">

					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
            			{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

        {% for message in messages %}
          <p id="messages">{{message}}</p>
        {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/accounts/navbar.html
{% load static %}

<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a href="{% url 'accounts:home' %}"><img src="{% static 'images/logo.svg' %}" alt="Logo" width="75" style="margin-right: 20px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if request.user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:home' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
      </li>
      {% else %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:account' %}">Settings</a>
      </li>
      {% endif %}
    </ul>
  </div>

  <span class="hello-msg" id="hello-msg">Hello, {{request.user}}</span>
  <span><a class="hello-msg" href="{% url 'accounts:logout' %}">Logout</a></span>
</nav>

accounts/templates/accounts/order_form.html
{% extends 'accounts/base_accounts.html' %}
{% load static %}

{% block content %}

<br>
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <form action="" method="POST">
        {% csrf_token %}
				{{ form.management_form }}
        {% for field in form %}
          {{field}}
          <hr>
        {% endfor %}
        <input type="submit" name="Submit">
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/product_form.html
{% extends 'accounts/base_accounts.html' %}
{% load static %}

{% block content %}

<br>
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <form action="" method="POST">
        {% csrf_token %}
				{{ form.management_form }}
        {% for field in form %}
          {{field.as_p}}
          <hr>
        {% endfor %}
        <input type="submit" name="Submit">
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/products.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}
    <br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Products</h5>
          <!-- <a class="btn btn-primary" href="{% url 'accounts:create_product' %}">Hello</a> -->
				</div>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Price</th>
						</tr>

            {% for i in products %}
              <tr>
                <td>{{i.name}}</td>
                <td>{{i.category}}</td>
                <td>{{i.price}}</td>
              </tr>
            {% endfor %}

					</table>
				</div>
			</div>
		</div>

{% endblock %}

accounts/templates/accounts/status.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

accounts/templates/accounts/upload_form.html
{% extends 'accounts/base_accounts.html' %}
{% load static %}

{% block content %}

<br>
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      {% for message in messages %}
        <p id="messages">{{message}}</p>
      {% endfor %}
      <form action="" method="POST" enctype ="multipart/form-data">
        {% csrf_token %}
          {{form.as_p}}
          <hr>
        <input type="submit" name="Submit">
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/user.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}

{%  include 'accounts/status.html' %}
<div class="row">


    <div class="col-md">
        <h5>LAST ORDERS</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                </tr>

                {% for o in orders %}
                  <tr>
                    <td>{{o.product}}</td>
                    <td>{{o.date_created}}</td>
                    <td>{{o.status}}</td>
                  </tr>
                {% endfor %}
            </table>
        </div>
    </div>
  </div>
{% endblock %}